<h1>LAB PROGRAM 7</h1>

Mithun G

19BTRCR006

<h2>a. Write Python program to find the addition of two matrices</h2>

In [2]:
# importing the numpy library
import numpy as np

In [18]:
# intializing the matrices
mat_a = np.array([[1,2],
                  [4,5]])

mat_b = np.array([[7,8],
                 [10,11]])

print("Matrix A:\n", mat_a)
print("\nMatrix B:\n", mat_b)

Matrix A:
 [[1 2]
 [4 5]]

Matrix B:
 [[ 7  8]
 [10 11]]


In [19]:
# addition of two matrices
print("Addition of matrices A and B:\n", mat_a + mat_b)

Addition of matrices A and B:
 [[ 8 10]
 [14 16]]


<h2>b. Write Python program to find the product of two matrices</h2>

In [20]:
print("hudmud multiplication of matrices:\n", mat_a*mat_b)
print()
print("Matrix multiplication of matices:\n", np.dot(mat_a, mat_b))

hudmud multiplication of matrices:
 [[ 7 16]
 [40 55]]

Matrix multiplication of matices:
 [[27 30]
 [78 87]]


<h2>c. Write Python program to find the transpose of a matrix</h2>

In [23]:
print("Original matrix A:\n", mat_a)
print("\nTranspose of matrix A:\n", mat_a.T)

Original matrix A:
 [[1 2]
 [4 5]]

Transpose of matrix A:
 [[1 4]
 [2 5]]
